update test script

diff --git a/test/extra_data_test b/test/extra_data_test
--- a/test/extra_data_test
+++ b/test/extra_data_test
@@ -1,15 +1,18 @@
 #!/bin/bash
-
+set -e
 ## file system
 normal_fs="ext2 ext3 ext4 vfat"
 featured_fs="$normal_fs jfs xfs reiserfs hfsplus"
-extra_fs="$featured_fs ufs vmfs reiser4 ntfs btrfs"
+extra_fs="$featured_fs ntfs btrfs"
+read_only_fs="ufs reiser4 vmfs"
 
 mkfs_option_for_reiserfs='-f'
 mkfs_option_for_ntfs='-f -F'
+mkfs_option_for_jfs='-f'
 
 test_fs=$extra_fs
 
+#FIXME
 USAGE() {
     cat << EOF
 	recognized flags are:
@@ -25,8 +28,18 @@ EOF
     
 }
 
+prefix_name(){
+    echo `date +%F-%H-%M`
+}
+
 abs_path(){
-    echo `cd $1;pwd`    
+    dy_path=$1
+    if [ -d $dy_path ]; then
+	echo `cd $1;pwd`
+    else
+	echo 2 "directory($dy_path) not exist"
+	exit 2
+    fi
 }
 
 check_option(){
@@ -93,18 +106,20 @@ check_option(){
     done
 }
 
-prefix_name(){
-    echo `date +%F-%H-%M`
-}
-
 generate_test_data_md5(){
 
     cur_path=`pwd`
     target_md5=$row_file_path/test_data.md5
-    echo "create md5 for $fs file"
+    echo "create md5 file"
     cd $test_data_path
     find $test_data_path -type f -exec md5sum '{}' \; > $target_md5
     cd $cur_path
+
+    if [ -f $target_md5 ]; then
+    else
+	echo "generate md5 file error"
+	exit 2
+    fi
 }
 
 prepare_data(){
@@ -113,28 +128,34 @@ prepare_data(){
     target_mpt=$row_file_path/mpt.$fs
 
     target_device=`losetup -f`
-    echo "generate row file($target_file) as loop device($target_device) for $fs"
-    dd if=/dev/zero of=$target_file bs=1MB count=$partition_size
-    losetup $target_device  $target_file
+    echo "generate $target_file as loop device($target_device) for $fs test"
+    dd if=/dev/zero of=$target_file bs=1M count=$partition_size
+    losetup $target_device $target_file
 
     echo "format $target_device as $fs row partition"
     mkfs.$fs `eval echo "$"mkfs_option_for_$fs""` $target_device
 
+    echo "copy data to $target_mpt"
     mkdir -p $target_mpt
     mount $target_device $target_mpt
     rsync -avrl --delete $test_data_path $target_mpt
     umount $target_mpt
     losetup -d $target_device
+    echo "prepare data done"
 
 }
 
 check_source(){
     fs=$1
     target_file=$row_file_path/source_row_device.$fs
-    [ -f $target_file ] || exit
-    target_device=`losetup -f`
-    losetup $target_device  $target_file
-    echo $target_device
+    if [ -f $target_file ]; then
+	target_device=`losetup -f`
+	losetup $target_device  $target_file
+	echo $target_device
+    else
+	echo "can't find $target_file"
+	exit 2
+    fi
 }
 
 check_image(){
@@ -156,6 +177,8 @@ restore_data_check() {
     fs=$1
     target_md5=$row_file_path/test_data.md5
     target_mpt=$row_file_path/mpt.restore
+    [ -f $target_md5 ] || exit 2
+    [ -d $target_mpt ] || exit 2
     cur_path=`pwd`
     mkdir -p $target_mpt
     mount -o loop $target_device $target_mpt
@@ -173,12 +196,6 @@ restore_data_check() {
    
 }
 
-check_return_code(){
-    if [ $? != 0 ]; then
-	echo "return code fail"
-	exit
-    fi
-}
 #main
 
 check_option $@
@@ -201,15 +218,12 @@ for fs in $test_fs; do
 
     echo "clone $source_device to $partclone_img"
     partclone.$fs $debug $ncurses -c -s $source_device -O $partclone_img -L $logfile.clone
-    check_return_code
 
     echo "do image checking"
     partclone.chkimg -s $partclone_img -L $logfile.imgchk
-    check_return_code
 
     echo "restore $partclone_img to $target_device"
     partclone.restore -s $partclone_img -o $target_device --restore_row_file -L $logfile.restore
-    check_return_code
 
     echo "md5 check"
     restore_data_check $fs
