Add get_ntfs_version, src/ntfs_version.c to check libntfs version. update src/ntfsclone-ng.c for bitmap bug
git-svn-id: svn+ssh://140.110.240.196/partclone_svn@164 93b75dfe-da2d-4241-a08d-2141769abc04

diff --git a/partclone/configure b/partclone/configure
--- a/partclone/configure
+++ b/partclone/configure
@@ -8618,8 +8618,8 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
 _ACEOF
 
 else
-  { { echo "$as_me:$LINENO: error: *** NTFS header not found" >&5
-echo "$as_me: error: *** NTFS header not found" >&2;}
+  { { echo "$as_me:$LINENO: error: *** NTFS(ntfsprog) header not found" >&5
+echo "$as_me: error: *** NTFS(ntfsprog) header not found" >&2;}
    { (exit 1); exit 1; }; }
 
 { echo "$as_me:$LINENO: checking for ntfs_mount in -lntfs" >&5
