update confiure
git-svn-id: svn+ssh://140.110.240.196/partclone_svn@198 93b75dfe-da2d-4241-a08d-2141769abc04

diff --git a/partclone/configure b/partclone/configure
--- a/partclone/configure
+++ b/partclone/configure
@@ -8703,14 +8703,20 @@ done
 
 { echo "$as_me:$LINENO: checking version of libntfs" >&5
 echo $ECHO_N "checking version of libntfs... $ECHO_C" >&6; }
-ntfs_version=`gcc $srcdir/src/ntfs_version.c -o $srcdir/get_ntfs_version -lntfs`
-ntfs_version=`$srcdir/get_ntfs_version | cut -d':' -f1`
-ntfs_version_major=`$srcdir/get_ntfs_version | cut -d':' -f2`
-ntfs_version_minor=`$srcdir/get_ntfs_version | cut -d':' -f3`
+ntfs_version=`gcc $srcdir/src/deplib_version.c -o $srcdir/get_lib_version -lntfs -DNTFS`
+ntfs_version=`$srcdir/get_lib_version ntfs | cut -d':' -f1`
+ntfs_version_major=`$srcdir/get_lib_version ntfs | cut -d':' -f2`
+ntfs_version_minor=`$srcdir/get_lib_version ntfs | cut -d':' -f3`
 if test -z "$ntfs_version"; then
         ntfs_version="?"
 	ntfs_version_major="?"
 	ntfs_version_minor="?"
+	{ echo "$as_me:$LINENO: result: $ntfs_version" >&5
+echo "${ECHO_T}$ntfs_version" >&6; }
+        { { echo "$as_me:$LINENO: error: Please check your libntfs to 9:0:0 or newer version!" >&5
+echo "$as_me: error: Please check your libntfs to 9:0:0 or newer version!" >&2;}
+   { (exit 1); exit 1; }; }
+
 fi
 
 if test $ntfs_version -lt 9 ; then
