Unstable version.     add new filesystem: FAT16/32     add --enable-fat to compile clone.fat.     add --enable-all to compile all supported filesystem utilities.
git-svn-id: svn+ssh://140.110.240.196/partclone_svn@110 93b75dfe-da2d-4241-a08d-2141769abc04

diff --git a/partclone/configure b/partclone/configure
--- a/partclone/configure
+++ b/partclone/configure
@@ -728,6 +728,8 @@ ENABLE_REISER4_TRUE
 ENABLE_REISER4_FALSE
 ENABLE_HFSP_TRUE
 ENABLE_HFSP_FALSE
+ENABLE_FAT_TRUE
+ENABLE_FAT_FALSE
 ENABLE_STATIC_TRUE
 ENABLE_STATIC_FALSE
 LIBOBJS
@@ -1331,6 +1333,7 @@ Optional Features:
   --enable-reiserfs       enable REISERFS 3.6/3.6 file system
   --enable-reiser4        enable Reiser4 file system
   --enable-hfsp           enable HFS plus file system
+  --enable-fat            enable FAT file system
   --enable-static         enable static linking
 
 Optional Packages:
@@ -7506,6 +7509,7 @@ enable_xfs="yes"
 enable_reiserfs="yes"
 enable_reiser4="yes"
 enable_hfsp="yes"
+enable_fat="yes"
 fi
 
 ##XFS##
@@ -8426,6 +8430,25 @@ if test "$enable_hfsp" = yes; then
 supported_fs=$supported_fs" hfs-plus"
 fi
 
+##fat plus##
+# Check whether --enable-test was given.
+if test "${enable_test+set}" = set; then
+  enableval=$enable_test; enable_fat=yes
+fi
+
+ if test "$enable_fat" = yes; then
+  ENABLE_FAT_TRUE=
+  ENABLE_FAT_FALSE='#'
+else
+  ENABLE_FAT_TRUE='#'
+  ENABLE_FAT_FALSE=
+fi
+
+
+if test "$enable_fat" = yes; then
+supported_fs=$supported_fs" FAT"
+fi
+
 ##static linking##
 # Check whether --enable-test was given.
 if test "${enable_test+set}" = set; then
@@ -8443,7 +8466,7 @@ fi
 
 ac_config_headers="$ac_config_headers config.h"
 
-ac_config_files="$ac_config_files Makefile src/Makefile po/Makefile.in docs/Makefile docs/clone.extfs.8 docs/clone.hfsp.8 docs/clone.reiserfs.8 docs/clone.reiser4.8 docs/clone.xfs.8"
+ac_config_files="$ac_config_files Makefile src/Makefile po/Makefile.in docs/Makefile docs/clone.extfs.8 docs/clone.hfsp.8 docs/clone.fat.8 docs/clone.reiserfs.8 docs/clone.reiser4.8 docs/clone.xfs.8"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -8594,6 +8617,13 @@ if test -z "${ENABLE_HFSP_TRUE}" && test -z "${ENABLE_HFSP_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"ENABLE_HFSP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"ENABLE_HFSP\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ENABLE_FAT_TRUE}" && test -z "${ENABLE_FAT_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_FAT\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ENABLE_FAT\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -9087,6 +9117,7 @@ do
     "docs/Makefile") CONFIG_FILES="$CONFIG_FILES docs/Makefile" ;;
     "docs/clone.extfs.8") CONFIG_FILES="$CONFIG_FILES docs/clone.extfs.8" ;;
     "docs/clone.hfsp.8") CONFIG_FILES="$CONFIG_FILES docs/clone.hfsp.8" ;;
+    "docs/clone.fat.8") CONFIG_FILES="$CONFIG_FILES docs/clone.fat.8" ;;
     "docs/clone.reiserfs.8") CONFIG_FILES="$CONFIG_FILES docs/clone.reiserfs.8" ;;
     "docs/clone.reiser4.8") CONFIG_FILES="$CONFIG_FILES docs/clone.reiser4.8" ;;
     "docs/clone.xfs.8") CONFIG_FILES="$CONFIG_FILES docs/clone.xfs.8" ;;
@@ -9306,13 +9337,15 @@ ENABLE_REISER4_TRUE!$ENABLE_REISER4_TRUE$ac_delim
 ENABLE_REISER4_FALSE!$ENABLE_REISER4_FALSE$ac_delim
 ENABLE_HFSP_TRUE!$ENABLE_HFSP_TRUE$ac_delim
 ENABLE_HFSP_FALSE!$ENABLE_HFSP_FALSE$ac_delim
+ENABLE_FAT_TRUE!$ENABLE_FAT_TRUE$ac_delim
+ENABLE_FAT_FALSE!$ENABLE_FAT_FALSE$ac_delim
 ENABLE_STATIC_TRUE!$ENABLE_STATIC_TRUE$ac_delim
 ENABLE_STATIC_FALSE!$ENABLE_STATIC_FALSE$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 20; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 22; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
