add unstable/src/deplib_version.c to replace unstable/src/ntfs_version.c update configure to check library version ex: reiser4, reiserfs, extfs and ntfs.
git-svn-id: svn+ssh://140.110.240.196/partclone_svn@196 93b75dfe-da2d-4241-a08d-2141769abc04

diff --git a/unstable/configure b/unstable/configure
--- a/unstable/configure
+++ b/unstable/configure
@@ -715,11 +715,13 @@ LTLIBINTL
 POSUB
 RM
 LN_S
+ENABLE_ALL_TRUE
+ENABLE_ALL_FALSE
+ENABLE_EXTFS_TRUE
+ENABLE_EXTFS_FALSE
 CPP
 GREP
 EGREP
-ENABLE_ALL_TRUE
-ENABLE_ALL_FALSE
 ENABLE_XFS_TRUE
 ENABLE_XFS_FALSE
 ENABLE_REISERFS_TRUE
@@ -1333,6 +1335,7 @@ Optional Features:
   --disable-rpath         do not hardcode runtime library paths
   --disable-largefile     omit support for large files
   --enable-all            enable all supported file system
+  --enable-extfs          enable ext2/3/4 file system
   --enable-xfs            enable XFS file system
   --enable-reiserfs       enable REISERFS 3.6/3.6 file system
   --enable-reiser4        enable Reiser4 file system
@@ -6630,8 +6633,48 @@ fi
 
 
 
-supported_fs="ext2/3"
+supported_fs=""
+##enable-all##
+# Check whether --enable-test was given.
+if test "${enable_test+set}" = set; then
+  enableval=$enable_test; enable_all=yes
+fi
+
+ if test "$enable_all" = yes; then
+  ENABLE_ALL_TRUE=
+  ENABLE_ALL_FALSE='#'
+else
+  ENABLE_ALL_TRUE='#'
+  ENABLE_ALL_FALSE=
+fi
+
+if test "$enable_all" = "yes"; then
+enable_xfs="yes"
+enable_extfs="yes"
+enable_reiserfs="yes"
+enable_reiser4="yes"
+enable_hfsp="yes"
+enable_fat="yes"
+enable_ntfs="yes"
+fi
+
 ##ext2/3##
+# Check whether --enable-test was given.
+if test "${enable_test+set}" = set; then
+  enableval=$enable_test; enable_extfs=yes
+fi
+
+ if test "$enable_extfs" = yes; then
+  ENABLE_EXTFS_TRUE=
+  ENABLE_EXTFS_FALSE='#'
+else
+  ENABLE_EXTFS_TRUE='#'
+  ENABLE_EXTFS_FALSE=
+fi
+
+
+if test "$enable_extfs" = "yes"; then
+#check library of some filesystems
 { echo "$as_me:$LINENO: checking  for EXT2/3 Library and Header files ... ..." >&5
 echo "$as_me: checking  for EXT2/3 Library and Header files ... ..." >&6;}
 ac_ext=c
@@ -7495,29 +7538,47 @@ echo "$as_me: error: *** EXT2/3 library (libext2fs) not found" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
-
-##enable-all##
-# Check whether --enable-test was given.
-if test "${enable_test+set}" = set; then
-  enableval=$enable_test; enable_all=yes
+{ echo "$as_me:$LINENO: checking version of libextfs" >&5
+echo $ECHO_N "checking version of libextfs... $ECHO_C" >&6; }
+extfs_version=`gcc $srcdir/src/deplib_version.c -o $srcdir/get_lib_version -lext2fs -DEXTFS`
+extfs_version=`$srcdir/get_lib_version extfs | cut -d'.' -f1`
+extfs_version_major=`$srcdir/get_lib_version extfs | cut -d'.' -f2`
+extfs_version_minor=`$srcdir/get_lib_version extfs | cut -d'.' -f3`
+if test -z "$extfs_version"; then
+    extfs_version="?"
+    extfs_version_major="?"
+    extfs_version_minor="?"
+    extfs_version="$extfs_version.$extfs_version_major.$extfs_version_minor; bad"
+    { echo "$as_me:$LINENO: result: $extfs_version" >&5
+echo "${ECHO_T}$extfs_version" >&6; }
+    { { echo "$as_me:$LINENO: error: Please check your libextfs!" >&5
+echo "$as_me: error: Please check your libextfs!" >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
- if test "$enable_all" = yes; then
-  ENABLE_ALL_TRUE=
-  ENABLE_ALL_FALSE='#'
+if test $extfs_version -lt 1 ; then
+    extfs_version="$extfs_version.$extfs_version_major.$extfs_version_minor; bad"
+    { echo "$as_me:$LINENO: result: $extfs_version" >&5
+echo "${ECHO_T}$extfs_version" >&6; }
+    { { echo "$as_me:$LINENO: error: Please upgrade your libextfs to 1.41.3 or newer version!" >&5
+echo "$as_me: error: Please upgrade your libextfs to 1.41.3 or newer version!" >&2;}
+   { (exit 1); exit 1; }; }
+elif test $extfs_version -ge 1 -a $extfs_version_major -lt 41  ; then
+    extfs_version="$extfs_version.$extfs_version_major.$extfs_version_minor; suggest you upgrade the library!"
+    { echo "$as_me:$LINENO: result: $extfs_version" >&5
+echo "${ECHO_T}$extfs_version" >&6; }
+    { { echo "$as_me:$LINENO: error: Please upgrade your libextfs to 1.41.3 or newer version!" >&5
+echo "$as_me: error: Please upgrade your libextfs to 1.41.3 or newer version!" >&2;}
+   { (exit 1); exit 1; }; }
 else
-  ENABLE_ALL_TRUE='#'
-  ENABLE_ALL_FALSE=
+    extfs_version="$extfs_version.$extfs_version_major.$extfs_version_minor; ok!"
+    { echo "$as_me:$LINENO: result: $extfs_version" >&5
+echo "${ECHO_T}$extfs_version" >&6; }
 fi
+supported_fs=$supported_fs" extfs"
 
-if test "$enable_all" = "yes"; then
-enable_xfs="yes"
-enable_reiserfs="yes"
-enable_reiser4="yes"
-enable_hfsp="yes"
-enable_fat="yes"
-enable_ntfs="yes"
 fi
+#end of check extfs
 
 ##XFS##
 # Check whether --enable-test was given.
@@ -7767,6 +7828,7 @@ done
 
 supported_fs=$supported_fs" xfs"
 fi
+#end of check xfs
 
 ##reiserfs##
 # Check whether --enable-test was given.
@@ -8087,9 +8149,49 @@ echo "$as_me: error: *** Reiserfs depend library (libdal) not found" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
+{ echo "$as_me:$LINENO: checking version of libreiserfs" >&5
+echo $ECHO_N "checking version of libreiserfs... $ECHO_C" >&6; }
+reiserfs_version=`gcc $srcdir/src/deplib_version.c -o $srcdir/get_lib_version -lreiserfs -DREISERFS`
+reiserfs_version=`$srcdir/get_lib_version reiserfs | cut -d'.' -f1`
+reiserfs_version_major=`$srcdir/get_lib_version reiserfs | cut -d'.' -f2`
+reiserfs_version_minor=`$srcdir/get_lib_version reiserfs | cut -d'.' -f3`
+reiserfs_version_minor_2=`$srcdir/get_lib_version reiserfs | cut -d'.' -f4`
+if test -z "$reiserfs_version"; then
+    reiserfs_version="?"
+    reiserfs_version_major="?"
+    reiserfs_version_minor="?"
+    reiserfs_version_minor_2="?"
+    reiserfs_version="$reiserfs_version.$reiserfs_version_major.$reiserfs_version_minor.$reiserfs_version_minor_2; bad"
+    { echo "$as_me:$LINENO: result: $reiserfs_version" >&5
+echo "${ECHO_T}$reiserfs_version" >&6; }
+    { { echo "$as_me:$LINENO: error: Please check your libreiserfs!" >&5
+echo "$as_me: error: Please check your libreiserfs!" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+if test $reiserfs_version_major -lt 3 ; then
+    reiserfs_version="$reiserfs_version.$reiserfs_version_major.$reiserfs_version_minor.$reiserfs_version_minor_2; bad"
+    { echo "$as_me:$LINENO: result: $reiserfs_version" >&5
+echo "${ECHO_T}$reiserfs_version" >&6; }
+    { { echo "$as_me:$LINENO: error: Please upgrade your libreiserfs to 0.3.0.5 or newer version!" >&5
+echo "$as_me: error: Please upgrade your libreiserfs to 0.3.0.5 or newer version!" >&2;}
+   { (exit 1); exit 1; }; }
+elif test $reiserfs_version_major -ge 3 -a $reiserfs_version_minor_2 -lt 5  ; then
+    reiserfs_version="$reiserfs_version.$reiserfs_version_major.$reiserfs_version_minor.$reiserfs_version_minor_2; suggest you upgrade the library!"
+    { echo "$as_me:$LINENO: result: $reiserfs_version" >&5
+echo "${ECHO_T}$reiserfs_version" >&6; }
+    { { echo "$as_me:$LINENO: error: Please upgrade your libreiserfs to 0.3.0.5 or newer version!" >&5
+echo "$as_me: error: Please upgrade your libreiserfs to 0.3.0.5 or newer version!" >&2;}
+   { (exit 1); exit 1; }; }
+else
+    reiserfs_version="$reiserfs_version.$reiserfs_version_major.$reiserfs_version_minor.$reiserfs_version_minor_2; ok!"
+    { echo "$as_me:$LINENO: result: $reiserfs_version" >&5
+echo "${ECHO_T}$reiserfs_version" >&6; }
+fi
 supported_fs=$supported_fs" reiserfs"
 
 fi
+#end of check reiserfs
 
 ##reiser4##
 # Check whether --enable-test was given.
@@ -8414,9 +8516,46 @@ echo "$as_me: error: *** Reiser4 depend library (libaal) not found" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
-#end of check fs
+{ echo "$as_me:$LINENO: checking version of libreiser4" >&5
+echo $ECHO_N "checking version of libreiser4... $ECHO_C" >&6; }
+reiser4_version=`gcc $srcdir/src/deplib_version.c -o $srcdir/get_lib_version -lreiser4 -laal -DREISER4`
+reiser4_version=`$srcdir/get_lib_version reiser4 | cut -d'.' -f1`
+reiser4_version_major=`$srcdir/get_lib_version reiser4 | cut -d'.' -f2`
+reiser4_version_minor=`$srcdir/get_lib_version reiser4 | cut -d'.' -f3`
+if test -z "$reiser4_version"; then
+    reiser4_version="?"
+    reiser4_version_major="?"
+    reiser4_version_minor="?"
+    reiser4_version="$reiser4_version.$reiser4_version_major.$reiser4_version_minor; bad"
+    { echo "$as_me:$LINENO: result: $reiser4_version" >&5
+echo "${ECHO_T}$reiser4_version" >&6; }
+    { { echo "$as_me:$LINENO: error: Please check your libreiser4!" >&5
+echo "$as_me: error: Please check your libreiser4!" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+if test $reiser4_version -lt 1 ; then
+    reiser4_version="$reiser4_version.$reiser4_version_major.$reiser4_version_minor; bad"
+    { echo "$as_me:$LINENO: result: $reiser4_version" >&5
+echo "${ECHO_T}$reiser4_version" >&6; }
+    { { echo "$as_me:$LINENO: error: Please upgrade your libreiser4 to 1.0.6 or newer version!" >&5
+echo "$as_me: error: Please upgrade your libreiser4 to 1.0.6 or newer version!" >&2;}
+   { (exit 1); exit 1; }; }
+elif test $reiser4_version -ge 1 -a $reiser4_version_minor -lt 6  ; then
+    reiser4_version="$reiser4_version.$reiser4_version_major.$reiser4_version_minor; suggest you upgrade the library!"
+    { echo "$as_me:$LINENO: result: $reiser4_version" >&5
+echo "${ECHO_T}$reiser4_version" >&6; }
+    { { echo "$as_me:$LINENO: error: Please upgrade your libreiser4 to 1.0.6 or newer version!" >&5
+echo "$as_me: error: Please upgrade your libreiser4 to 1.0.6 or newer version!" >&2;}
+   { (exit 1); exit 1; }; }
+else
+    reiser4_version="$reiser4_version.$reiser4_version_major.$reiser4_version_minor; ok!"
+    { echo "$as_me:$LINENO: result: $reiser4_version" >&5
+echo "${ECHO_T}$reiser4_version" >&6; }
+fi
 supported_fs=$supported_fs" reiser4"
 fi
+#end of check reiser4
 
 ##hfs plus##
 # Check whether --enable-test was given.
@@ -8436,8 +8575,9 @@ fi
 if test "$enable_hfsp" = yes; then
 supported_fs=$supported_fs" hfs-plus"
 fi
+#end of check hfsplus
 
-##fat plus##
+##fat##
 # Check whether --enable-test was given.
 if test "${enable_test+set}" = set; then
   enableval=$enable_test; enable_fat=yes
@@ -8455,6 +8595,7 @@ fi
 if test "$enable_fat" = yes; then
 supported_fs=$supported_fs" fat"
 fi
+#end of check fat
 
 ##NTFS##
 # Check whether --enable-test was given.
@@ -8703,14 +8844,20 @@ done
 
 { echo "$as_me:$LINENO: checking version of libntfs" >&5
 echo $ECHO_N "checking version of libntfs... $ECHO_C" >&6; }
-ntfs_version=`gcc $srcdir/src/ntfs_version.c -o $srcdir/get_ntfs_version -lntfs`
-ntfs_version=`$srcdir/get_ntfs_version | cut -d':' -f1`
-ntfs_version_major=`$srcdir/get_ntfs_version | cut -d':' -f2`
-ntfs_version_minor=`$srcdir/get_ntfs_version | cut -d':' -f3`
+ntfs_version=`gcc $srcdir/src/deplib_version.c -o $srcdir/get_lib_version -lntfs -DNTFS`
+ntfs_version=`$srcdir/get_lib_version ntfs | cut -d':' -f1`
+ntfs_version_major=`$srcdir/get_lib_version ntfs | cut -d':' -f2`
+ntfs_version_minor=`$srcdir/get_lib_version ntfs | cut -d':' -f3`
 if test -z "$ntfs_version"; then
-        ntfs_version="?"
-	ntfs_version_major="?"
-	ntfs_version_minor="?"
+    ntfs_version="?"
+    ntfs_version_major="?"
+    ntfs_version_minor="?"
+    ntfs_version="$ntfs_version:$ntfs_version_major:$ntfs_version_minor; bad"
+    { echo "$as_me:$LINENO: result: $ntfs_version" >&5
+echo "${ECHO_T}$ntfs_version" >&6; }
+    { { echo "$as_me:$LINENO: error: Please check your libntfs!" >&5
+echo "$as_me: error: Please check your libntfs!" >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 if test $ntfs_version -lt 9 ; then
@@ -8732,6 +8879,7 @@ fi
 
 supported_fs=$supported_fs" ntfs"
 fi
+#end of check ntfs
 
 
 ##libncursesw##
@@ -9121,6 +9269,13 @@ if test -z "${ENABLE_ALL_TRUE}" && test -z "${ENABLE_ALL_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"ENABLE_ALL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"ENABLE_ALL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ENABLE_EXTFS_TRUE}" && test -z "${ENABLE_EXTFS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_EXTFS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ENABLE_EXTFS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -9871,11 +10026,13 @@ for ac_last_try in false false false false false :; do
 POSUB!$POSUB$ac_delim
 RM!$RM$ac_delim
 LN_S!$LN_S$ac_delim
+ENABLE_ALL_TRUE!$ENABLE_ALL_TRUE$ac_delim
+ENABLE_ALL_FALSE!$ENABLE_ALL_FALSE$ac_delim
+ENABLE_EXTFS_TRUE!$ENABLE_EXTFS_TRUE$ac_delim
+ENABLE_EXTFS_FALSE!$ENABLE_EXTFS_FALSE$ac_delim
 CPP!$CPP$ac_delim
 GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
-ENABLE_ALL_TRUE!$ENABLE_ALL_TRUE$ac_delim
-ENABLE_ALL_FALSE!$ENABLE_ALL_FALSE$ac_delim
 ENABLE_XFS_TRUE!$ENABLE_XFS_TRUE$ac_delim
 ENABLE_XFS_FALSE!$ENABLE_XFS_FALSE$ac_delim
 ENABLE_REISERFS_TRUE!$ENABLE_REISERFS_TRUE$ac_delim
@@ -9896,7 +10053,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 26; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 28; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
