try to add partclone.zfs

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -21,11 +21,11 @@ jobs:
           sudo apt-get update
           sudo apt-get build-dep partclone
           sudo apt-get install build-essential autoconf automake autotools-dev libtool libtool-bin gettext intltool pkg-config
-          sudo apt-get install f2fs-tools hfsprogs exfatprogs gddrescue reiser4progs libxxhash-dev libisal-dev liburcu-dev btrfs-progs
+          sudo apt-get install f2fs-tools hfsprogs exfatprogs gddrescue reiser4progs libxxhash-dev libisal-dev liburcu-dev btrfs-progs libzfslinux-dev libudev-dev
     - name: automake
       run: ./autogen
     - name: configure
-      run: ./configure --enable-fs-test --enable-feature-test --enable-extfs --enable-ntfs --enable-fat --enable-exfat --enable-hfsp --enable-apfs --enable-btrfs --enable-minix --enable-f2fs --enable-reiser4 --enable-xfs --enable-xxhash --enable-isal
+      run: ./configure --enable-fs-test --enable-feature-test --enable-extfs --enable-ntfs --enable-fat --enable-exfat --enable-hfsp --enable-apfs --enable-btrfs --enable-minix --enable-f2fs --enable-reiser4 --enable-xfs --enable-xxhash --enable-isal --enable-zfs
     - name: make
       run: make
     - name: makeTest
@@ -36,6 +36,13 @@ jobs:
         ldd src/partclone.extfs
         nm src/partclone.extfs | grep " T main"
         if file src/partclone.extfs | grep -q "statically linked"; then
+          echo "Error: Binary is statically linked but expected dynamic."
+          exit 1
+        fi
+        file src/partclone.zfs
+        ldd src/partclone.zfs
+        nm src/partclone.zfs | grep " T main"
+        if file src/partclone.zfs | grep -q "statically linked"; then
           echo "Error: Binary is statically linked but expected dynamic."
           exit 1
         fi
